language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t ahmed0famous/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ahmed0famous/react-test npm run test


after_success:
  - docker build -t ahmed0famous/multi-client ./client
  - docker build -t ahmed0famous/multi-nginx ./nginx
  - docker build -t ahmed0famous/multi-server ./server
  - docker build -t ahmed0famous/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  # Take those images and push them to docker hub
  - docker push ahmed0famous/multi-client
  - docker push ahmed0famous/multi-nginx
  - docker push ahmed0famous/multi-server
  - docker push ahmed0famous/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env-1'
  bucket_name: 'elasticbeanstalk-us-east-1-744264140678'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY